"use client";
import { useState } from "react";
import Link from "next/link"; import { ArrowUpRight, Download, BarChart3, ShieldCheck, Layers3, BrainCircuit } from "lucide-react"; import { SectionHeading } from "./SectionHeading"; import { services, process, site } from "@/data/site";

export function About() { const [tab, setTab] = useState("Overview"); const data = { Overview: ["I build complete digital products across frontend, backend and AI integration.", "My focus is reusable architecture, fast interfaces and clear user flows."], Timeline: ["2025 — Present · Shaadi Software Technology · Delhi", "2023 — 2025 · Webkype Info Services · Noida", "2020 — 2023 · BCA · NIET / Noida"], Philosophy: ["Understand the problem before writing code.", "Keep components reusable and APIs predictable.", "Ship a useful version, measure it, then improve."] }[tab as "Overview" | "Timeline" | "Philosophy"]; return <section id="about" className="section-space"><div className="container-pro"><SectionHeading index="02 / ABOUT" title="More than a stack of technologies." text="A recruiter-friendly view of how I think, build and collaborate." /><div className="grid gap-6 lg:grid-cols-[1fr_1.1fr]"><div className="about-art rounded-[32px] p-7 text-white md:p-10"><span className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Developer profile</span><h3 className="mt-5 font-display text-4xl font-black">Build. Integrate. Improve.</h3><p className="mt-5 max-w-lg leading-7 text-white/55">AI • MERN • Full Stack developer focused on useful software and production-ready experiences.</p><div className="mt-8 rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="text-xs font-bold uppercase tracking-[.16em] text-white/45">What matters</p><p className="mt-2 text-sm leading-6 text-white/65">Reusable architecture, clear APIs, responsive UI and practical AI integration.</p></div></div><div className="surface p-6 md:p-8"><div className="flex flex-wrap gap-2">{["Overview", "Timeline", "Philosophy"].map(x => <button key={x} onClick={() => setTab(x)} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${tab === x ? "bg-black text-white dark:bg-white dark:text-black" : "bg-black/5 dark:bg-white/5"}`}>{x}</button>)}</div><div className="mt-7 space-y-4">{data.map((x, i) => <div key={x} className="flex gap-4 rounded-2xl bg-black/[.035] p-5 dark:bg-white/[.035]"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-violet-500/10 text-violet-600">{i + 1}</span><p className="leading-7">{x}</p></div>)}</div></div></div></div></section> }

export function Services() { return <section id="services" className="section-space bg-black/[.025] dark:bg-white/[.015]"><div className="container-pro"><SectionHeading index="03 / SERVICES" title="What I can build." text="Clear service areas for recruiters, founders and teams." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{services.map((s, i) => <div key={s.title} className="surface p-6"><span className="font-mono text-xs text-violet-600">0{i + 1}</span><h3 className="mt-5 font-display text-xl font-black">{s.title}</h3><p className="mt-3 text-sm leading-6 text-black/50 dark:text-white/50">{s.desc}</p><div className="mt-6 h-px bg-black/10 dark:bg-white/10" /><p className="mt-4 text-xs font-bold text-violet-600">AVAILABLE</p></div>)}</div></div></section> }

export function Process() { return <section id="process" className="section-space"><div className="container-pro"><SectionHeading index="09 / PROCESS" title="How projects move." text="A simple delivery system that keeps scope, quality and communication visible." /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{process.map((x, i) => <div key={x} className="surface relative p-5"><span className="font-mono text-xs text-violet-600">0{i + 1}</span><h3 className="mt-8 font-display text-xl font-black">{x}</h3><p className="mt-2 text-xs leading-5 text-black/45 dark:text-white/45">Clear milestone and useful output.</p></div>)}</div></div></section> }

export function Achievements() { const a = [[BarChart3, "Performance", "Focused on faster interfaces and efficient API workflows."], [ShieldCheck, "Quality", "Validation, reusable components and production-minded structure."], [Layers3, "Architecture", "Reusable UI, clear routes and modular project organization."], [BrainCircuit, "AI", "Practical AI assistants and product integrations."]]; return <section id="highlights" className="section-space bg-black/[.025] dark:bg-white/[.015]"><div className="container-pro"><SectionHeading index="11 / HIGHLIGHTS" title="Engineering highlights." text="The details recruiters usually want to see after the headline." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{a.map(([I, t, d]) => { const Icon = I as typeof BarChart3; return <div key={t as string} className="surface p-6"><Icon className="text-violet-600" size={22} /><h3 className="mt-6 font-display text-xl font-black">{t as string}</h3><p className="mt-3 text-sm leading-6 text-black/50 dark:text-white/50">{d as string}</p></div> })}</div></div></section> }

export function RecruiterCTA() { return <section className="pb-24"><div className="container-pro"><div className="overflow-hidden rounded-[34px] bg-gradient-to-br from-violet-700 via-fuchsia-600 to-cyan-500 p-[1px]"><div className="rounded-[33px] bg-[#101116] p-7 text-white md:p-10"><div className="flex flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">12 / NEXT STEP</p><h2 className="mt-3 font-display text-4xl font-black md:text-5xl">Looking for an AI + Full Stack developer?</h2><p className="mt-4 max-w-2xl text-white/50">Review the work, open a case study, or start a conversation about your product.</p></div><div className="flex flex-wrap gap-3"><a href={site.resume} download className="inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3.5 font-bold text-black"><Download size={17} />Resume</a><Link href="/contact" className="inline-flex items-center gap-2 rounded-2xl bg-violet-500 px-5 py-3.5 font-bold text-white">Hire me <ArrowUpRight size={17} /></Link></div></div></div></div></div></section> }
